[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "CircuitPython_OPT4003"
authors = [{name = "Neil Khera", email = "nkhera@andrew.cmu.edu"}]
dynamic = ["0.1.0", "CircuitPython driver for the OPT4003 ambient light sensor"]